# Generated by Django 4.2.29 on 2026-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('RUB', '₽')], default='EUR', max_length=3),
        ),
    ]
