# Generated by Django 4.2.29 on 2026-04-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('EUR', '€'), ('USD', '$')], default='RUB', max_length=3),
        ),
    ]
