# Generated by Django 4.2.29 on 2026-05-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_category_name_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_type',
            field=models.CharField(blank=True, choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.category'),
        ),
    ]
