# Generated by Django 4.2.29 on 2026-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_transaction_category_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
