# Generated by Django 4.2.29 on 2026-05-12 21:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0012_alter_category_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_type',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),
    ]
