# Generated by Django 4.2.29 on 2026-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_account_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('deposit', 'Вклад/Счет'), ('credit', 'Кредитная карта'), ('other', 'Другое')], default='cash', max_length=20),
        ),
    ]
